spring:
  application:
    name: engenhariaGB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/engenharia-gb
    username: postgres
    password: totvs@123